[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.11.0"
rstest = "0.26.1"

[dev-dependencies]
divan = "0.1.21"

[lib]
path = "src/lib.rs"

[[bench]]
name = "benchmarks"
path = "src/benches/benchmarks.rs"
harness = false
